-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 19:06:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Smart_Sports_Predictor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Smart_Sports_Predictor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Smart_Sports_Predictor` ;
USE `Smart_Sports_Predictor` ;

-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`ipldata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`ipldata` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `team1` VARCHAR(45) NOT NULL,
  `team2` VARCHAR(45) NOT NULL,
  `winner` VARCHAR(45) NOT NULL,
  `margin` VARCHAR(45) NULL,
  `ground` VARCHAR(45) NULL,
  `match_date` DATE NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email_id` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`dashboard` (
  `dashboard_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email_id` VARCHAR(50) NOT NULL,
  `matches_played` INT NULL,
  `runs_scored` INT NULL,
  `wicket_taken` INT NULL,
  PRIMARY KEY (`dashboard_id`),
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE,
  CONSTRAINT `email_id`
    FOREIGN KEY (`email_id`)
    REFERENCES `Smart_Sports_Predictor`.`users` (`email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
