-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 20:23:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Smart_Sports_Predictor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Smart_Sports_Predictor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Smart_Sports_Predictor` ;
USE `Smart_Sports_Predictor` ;

-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`ipldata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Smart_Sports_Predictor`.`ipldata` ;

CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`ipldata` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `season` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `match_date` DATE NULL,
  `team1` VARCHAR(45) NOT NULL,
  `team2` VARCHAR(45) NOT NULL,
  `toss_winner` VARCHAR(45) NOT NULL,
  `toss_decision` VARCHAR(45) NOT NULL,
  `result` VARCHAR(45) NOT NULL,
  `dl_applied` INT NOT NULL,
  `winner` VARCHAR(45) NOT NULL,
  `win_by_runs` INT NOT NULL,
  `win_by_wickets` INT NOT NULL,
  `player_of_match` VARCHAR(45) NOT NULL,
  `venue` VARCHAR(85) NOT NULL,
  `umpire1` VARCHAR(45) NULL,
  `umpire2` VARCHAR(45) NULL,
  `umpire3` VARCHAR(45) NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Smart_Sports_Predictor`.`users` ;

CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email_id` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`dashboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Smart_Sports_Predictor`.`dashboard` ;

CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`dashboard` (
  `dashboard_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email_id` VARCHAR(50) NOT NULL,
  `matches_played` INT NULL,
  `runs_scored` INT NULL,
  `wicket_taken` INT NULL,
  PRIMARY KEY (`dashboard_id`),
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE,
  CONSTRAINT `email_id`
    FOREIGN KEY (`email_id`)
    REFERENCES `Smart_Sports_Predictor`.`users` (`email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Smart_Sports_Predictor`.`match_datasets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Smart_Sports_Predictor`.`match_datasets` ;

CREATE TABLE IF NOT EXISTS `Smart_Sports_Predictor`.`match_datasets` (
  `match_id` INT UNSIGNED NOT NULL,
  `inning` INT NOT NULL,
  `batting_team` VARCHAR(45) NOT NULL,
  `bowling_team` VARCHAR(45) NOT NULL,
  `over` INT NOT NULL,
  `ball` INT NOT NULL,
  `batsmen` VARCHAR(45) NOT NULL,
  `non_striker` VARCHAR(45) NOT NULL,
  `bowler` VARCHAR(45) NOT NULL,
  `is_super_over` INT NOT NULL,
  `wide_runs` INT NOT NULL,
  `bye_runs` INT NOT NULL,
  `legbye_runs` INT NOT NULL,
  `noball_runs` INT NOT NULL,
  `penalty_runs` INT NOT NULL,
  `batsmen_runs` INT NOT NULL,
  `extra_runs` INT NOT NULL,
  `total_runs` INT NOT NULL,
  `player_dismissed` VARCHAR(45) NULL,
  `dismissal_kind` VARCHAR(45) NULL,
  `fielder` VARCHAR(45) NULL,
  PRIMARY KEY (`match_id`),
  UNIQUE INDEX `match_id_UNIQUE` (`match_id` ASC) VISIBLE,
  CONSTRAINT `match_id`
    FOREIGN KEY ()
    REFERENCES `Smart_Sports_Predictor`.`ipldata` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
